###
POST http://localhost:3000/api/checkEmail
Content-Type: application/json

{
    "email" : "maxime.dubost.75@gmail.com"
}
###
POST http://localhost:3000/api/user/add
Content-Type: application/json

{
	"firstname" : "Chiara", 
	"lastname" : "Berardi", 
	"username" : "cberardi",
    "birthdate" : "2000-05-28 20:18:04Z",
    "phonenumber" : "0145696330",
	"email" : "chiara.berardi@gmail.com", 
	"password" : "motdepasse"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
	"connectId" : "kevin.tsi@gmail.com", 
	"password" : "Azerty1&"
}