###
GET http://localhost:3000/api/user/1


###
POST  http://localhost:3000/api/user/add
Content-Type: application/json

{
	"firstname" : "Christ", 
	"lastname" : "ULCE", 
	"username" : "ulce31",
    "birthdate" : "1999-12-31 00:00:00Z",
    "phonenumber" : "0629506187",
	"email" : "christ.ulce@gmail.com", 
	"password" : "P@ssw0rd"
}


###
POST http://localhost:3000/api/checkEmail
Content-Type: application/json

{
    "email" : "maxime.dubost.75@gmail.com"
}

###
PUT http://localhost:3000/api/user/update/8
Content-Type: application/json

{
	"firstname" : "Christ", 
	"lastname" : "ULCE", 
	"username" : "ulce31",
    "birthdate" : "1999-12-31 00:00:00Z",
    "phonenumber" : "0629506187",
	"email" : "christu.cu75@gmail.com", 
	"password" : "P@ssword"
}


###
POST http://localhost:3000/api/login
Content-Type: application/json

{
	"connectId" : "ulce31", 
	"password" : "P@ssw0rd"
}



###
DELETE http://localhost:3000/api/user/delete/4

###
POST http://localhost:3000/api/sendCode
Content-Type: application/json

{
	"email": "christ.ulce@gmail.com"
}

###
POST http://localhost:3000/api/checkCode
Content-Type: application/json

{
	"code": ""
}

###
PUT http://localhost:3000/api/resetPassword
Content-Type: application/json

{
	"email" : "christ.ulce@gmail.com", 
	"password" : "P@ssword&0"
}

###
POST http://localhost:3000/api/sendCode
Content-Type: application/json

{
	"email" : "christu.cu75@gmail.com"
}




### REQUESTS SESSION
GET http://localhost:3000/api/session/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjaGlhcmEuYmVyYXJkaUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNiZXJhcmRpIiwiaWF0IjoxNTg2NjE5MDUzfQ.oqfUBj0NMrba1To3qLMEOEimuba8CxBGbdCpt_f9ZzU

### 
GET http://localhost:3000/api/sessions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjaGlhcmEuYmVyYXJkaUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNiZXJhcmRpIiwiaWF0IjoxNTg2NjE5MDUzfQ.oqfUBj0NMrba1To3qLMEOEimuba8CxBGbdCpt_f9ZzU

###
POST http://localhost:3000/api/session
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjaHJpc3QudWxjZUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InVsY2UzMSIsImlhdCI6MTU4Njk0MzAyM30.rbsP0Za8igBTkSNxMMYF0hKJu5j25DC44ZE3wynOpzw
Content-Type: application/json

{
	"sessionName" : "TEST"
}

###
DELETE http://localhost:3000/api/session/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjaHJpc3QudWxjZUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InVsY2UzMSIsImlhdCI6MTU4NjYyMTE1NH0.eJYtYDXHkwnREu_1WPbSVHhZ49hYyAnAhApaFj2KGqs
Content-Type: application/json

###
PUT http://localhost:3000/api/session/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjaHJpc3QudWxjZUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InVsY2UzMSIsImlhdCI6MTU4NjYyMTE1NH0.eJYtYDXHkwnREu_1WPbSVHhZ49hYyAnAhApaFj2KGqs
Content-Type: application/json

{
	"sessionName" : "TEST 2"
}

###
GET http://localhost:3000/api/appexercises