INSERT INTO public._muscle(name)
	VALUES
	('Abdominaux'),
	('Avant-bras'),
	('Biceps'),
	('Dos'),
	('Épaules'),
	('Ischios'),
	('Mollets'),
	('Pectoraux'),
	('Quadriceps'),
	('Triceps');

INSERT INTO public._app_exercise(name)
	VALUES 
	('Crunch'),
	('Crunch à la poulie'),
	('Curls à la barre'),
	('Curls haltères'),
	('Curls poulie'),
	('Développés à la barre'),
	('Développés couché'),
	('Développés décliné'),
	('Développés épaules'),
	('Développés incliné'),
	('Dips'),
	('Dips entre deux bancs'),
	('Écartés haltères'),
	('Écartés poulies'),
	('Élévation à 45°'),
	('Élévation buste penché'),
	('Élévation frontale'),
	('Élévation latérale'),
	('Élévations frontales incliné'),
	('Extension à la poulie'),
	('Extension assis'),
	('Extension couché'),
	('Extension lombaire'),
	('Fentes'),
	('Flexion aux haltères'),
	('Flexion barre pronation'),
	('Flexion barre supination'),
	('Flexions latérales'),
	('Gainage'),
	('Good morning'),
	('Hack squat'),
	('Kickback'),
	('Leg curl assis'),
	('Leg curl debout'),
	('Leg extension'),
	('Mollets à la presse'),
	('Mollets assis'),
	('Mollets debout'),
	('Montée sur banc'),
	('Oiseau à la poulie'),
	('Pec-deck'),
	('Pompe'),
	('Presse à cuisse'),
	('Pullover'),
	('Relevés de jambes'),
	('Rotation avec bâton'),
	('Rowing'),
	('Rowing assis'),
	('Rowing barre T'),
	('Rowing deux haltères'),
	('Rowing haltère'),
	('Shrug'),
	('Shrug incliné haltères'),
	('Sissy squat'),
	('Soulevé de terre'),
	('Soulevé de terre jambes tendues'),
	('Squat'),
	('Squat barre guidée'),
	('Tirage horizontal'),
	('Tirage horizontal haut'),
	('Tirage menton'),
	('Tirage verticaux'),
	('Traction');

INSERT INTO public._app_exercise_muscle(id_app_exercise, id_muscle)
VALUES
	(1,	1),
	(2,	1),
	(3,	3),
	(4,	3),
	(5,	3),
	(6,	10),
	(7,	8),
	(8, 8),
	(9, 5),
	(10, 8),
	(11, 10),
	(12, 10),
	(13, 8),
	(14, 8),
	(15, 7),
	(16, 5),
	(17, 5),
	(18, 5),
	(19, 5),
	(20, 10),
	(21, 10),
	(22, 10),
	(23, 4),
	(24, 6),
	(25, 2),
	(26, 2),
	(27, 2),
	(28, 1),
	(29, 1),
	(30, 6),
	(31, 9),
	(32, 10),
	(33, 6),
	(34, 6),
	(35, 9),
	(36, 7),
	(37, 7),
	(38, 7),
	(39, 9),
	(40, 5),
	(41, 8),
	(42, 8),
	(43, 9),
	(44, 4),
	(45, 1),
	(46, 1),
	(47, 4),
	(48, 4),
	(49, 4),
	(50, 4),
	(51, 4),
	(52, 4),
	(53, 4),
	(54, 9),
	(55, 4),
	(56, 6),
	(57, 9),
	(58, 9),
	(59, 4),
	(60, 4),
	(61, 5),
	(62, 4),
	(63, 4);